import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

import './globals.css'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * Root layout component for the application.
 *
 * This component sets the base HTML structure for the application,
 * including setting the language attribute on the <html> element
 * and applying a class name to the <body> element.
 *
 * @param props - The properties object.
 * @param props.children - The child nodes to be rendered inside the <body> element.
 *
 * @returns The root layout of the application.
 */
export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
